version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app # For development: reflects code changes immediately
    env_file:
      - .env # Load environment variables from .env file
